### ISSUE TITLE
Can't get this to work

### ISSUE THREAD

**Issue by booshtukka** [gfk-ba/meteor-server-cookies#1]
I've tried exactly copying the example (which says Metheor by the way) but am having no luck. Is ServerCookies.ready() definitely a reactive source? It never seems to change or trigger autodeps. Help!

**Comment by travisdahl** [comment]
No luck for me either.

**Comment by tbknl** [comment]
Thanks for your feedback! And sorry for my late response.
I corrected the example in the readme. Please try it again. I'm interested to know whether it works for you now.
